DataBiosphere/clinvar-ingest

argo/workflow.yaml

Outputs of a successful test run are at `gs://broad-dsp-monster-dev-transporter-tmp/dan-test/VariationArchive/`

DSPDC-609 Mount SA credentials to enable GCS upload.

---

schema/src/main/jade-tables/release_history.table.json

Noticed the table was missing from the schema while I was prepping an example for HCA.

DSPDC-956 Fix specification of release_history table.

---

orchestration/templates/create-json-object.yaml
orchestration/templates/ingest-clinvar-archive.yaml

Added a new template - create-json-object to save release date and archive path (provided as params) to a json file and then rsnyc the file to the provided upload path.
Need to confirm that this is working as expected.

QH - DSPDC-804 - Stage a release_history object in GCS

---

orchestration/templates/ingest-clinvar-archive.yaml

Successful run here: https://argo.monster-dev.broadinstitute.org/workflows/clinvar/clinvar-ingest-kbdn9?tab=workflow&nodeId=clinvar-ingest-kbdn9-3493958296
Mostly a cut/paste to move the stage-release-history piece below the dependency of the xml-blob ingest, and then updated a few things to use the file-id output by the file-ingest step.

Ra dspdc 827 use drs id

---

orchestration/Chart.yaml
orchestration/templates/ingest-clinvar-archive.yaml
orchestration/templates/process-table.yaml

Combine the diff-table and ingest-table steps into one template, then call that template in the main workflow template. Add a condition so that the ingest-table step doesn't happen if there are no new rows to append.

Ra dspdc 1009 no rows

---

orchestration/templates/ingest-processed-archive.yaml

The diff is bigger than it could be because I reordered the steps to make soft-delete go first. The only meaningful difference is the addition to the `dependencies` of `ingest-table`

DSPDC-1103 Force ingest to run after soft-delete.

---

build.sbt
orchestration/example-values/no-version.yaml
orchestration/example-values/pinned-version.yaml
orchestration/scripts/poll-ingest-job.py
orchestration/scripts/request-full-view-snapshot.py
orchestration/templates/cron-workflow.yaml
orchestration/templates/ingest-clinvar-archive.yaml
orchestration/templates/ingest-processed-archive.yaml
orchestration/templates/ingest-raw-archive.yaml
orchestration/templates/process-clinvar-archive.yaml
orchestration/templates/snapshot-dataset.yaml
orchestration/values.schema.json
orchestration/values.yaml
project/plugins.sbt

I rearranged the values file as part of this to group things in a different way. The main motivation of that refactor was the need to have the user-defined dataset name as an argument (different from the existing arg for BQ dataset name). The BQ dataset name is derivable from the user-defined name, but our existing value name wasn't a good fit.
Here's an example of a successful run of the new WorkflowTemplate: https://argo.monster-dev.broadinstitute.org/archived-workflows/clinvar/14ae5bba-2ad8-4593-bc02-dc0f004e135e
Here's an example of full ingest run: https://argo.monster-dev.broadinstitute.org/workflows/clinvar/ingest-clinvar-archive-9mm27. I think we're hitting a bug in Jade's cleanup of old snapshots, because I deleted the 1st snapshot but the job is still failing from a duplicate …

DSPDC-908 Create a snapshot at the end of the workflow

---

schema/src/main/jade-assets/clinvar_release.asset.json
schema/src/main/jade-tables/clinical_assertion.table.json
schema/src/main/jade-tables/clinical_assertion_trait.table.json
schema/src/main/jade-tables/clinical_assertion_trait_set.table.json
schema/src/main/jade-tables/clinical_assertion_variation.table.json
schema/src/main/jade-tables/gene.table.json
schema/src/main/jade-tables/gene_association.table.json
schema/src/main/jade-tables/processing_history.table.json
schema/src/main/jade-tables/rcv_accession.table.json
schema/src/main/jade-tables/submission.table.json
schema/src/main/jade-tables/submitter.table.json
schema/src/main/jade-tables/trait.table.json
schema/src/main/jade-tables/trait_mapping.table.json
schema/src/main/jade-tables/trait_set.table.json
schema/src/main/jade-tables/variation.table.json
schema/src/main/jade-tables/variation_archive.table.json

I wrote up ideas for how to use the new processing_history table in the doc: https://docs.google.com/document/d/1rpbyWCAaJCWC4CfbGWOq5VwZp1eoYUqRh-szxJ4Sw5w/edit#heading=h.r2seu6gorax6
The checked-in asset is required for cutting snapshots of single ClinVar releases (by date). We don't have any tooling to generate assets yet, so we'll need to inject it manually for now.

DSPDC-1156 DSPDC-1149 Add processing_history table, release_date links.

---

transformation/src/main/scala/org/broadinstitute/monster/clinvar/Content.scala
transformation/src/test/scala/org/broadinstitute/monster/clinvar/ContentSpec.scala

I expect the test coverage will be poor here... there are a lot of "what if?" scenarios that are technically possible when comparing two `Msg` instances, but that I don't expect we'd ever see in practice.

DSPDC-1148 Canonicalize content during encoding.

---

.github/codecov.yaml

75% is better than most of our repos, but still feels attainable. Allowing a 5% drop in PRs feels realistic.

DSPDC-1130 Add codecov config.

---

docker/diff/build.sh
docker/diff/diff.py
orchestration/templates/date-absent.yaml
orchestration/templates/date-present.yaml

Update diff to insert pks for tables without `id` column, use updated image in workflow.
Tested the diffing on tables that had diffing generated correctly, those are still being generated and returning the same stuff as before. Now also works for gene_association and trait_mapping tables.

ra DSPDC 1311 diff bug

---

.github/codecov.yaml
.github/workflows/build-and-publish-master.yaml
.github/workflows/build-and-publish-release.yaml
.github/workflows/validate-pull-request.yaml
orchestration/Chart.yaml
orchestration/templates/ingest-xml-archive.yaml

We need to include a [load tag](https://github.com/databiosphere/stairway#concurrency) in our calls to jade's bulk ingest endpoint.
* Creates a load tag that is the path to the daily file for ingest. This will prevent us from ingesting the same file simultaneously to Jade.

Add load tag to bulk ingest call

---

.github/workflows/build-and-publish-release.yaml

We are unable to tag and release a clinvar version due to this [error](https://github.com/DataBiosphere/clinvar-ingest/actions/runs/501961762). 
* Works around the issue with by setting a magic env var, until we can figure out a better fix.

Set env var as a workaround for github action error

---

build.sbt

We cannot publish a docker container for this pipeline due to the needed docker image being unavailable. Upgrading ingest-utils to 2.1.8 causes codegen issues on our usage of the scala reserved keyword `trait` for one of the entities we model. Until we can figure _that_ out, let's try just overriding the docker image in the build.sbt settings.
* Overrides the `dockerBaseImage` setting to point at the CE graalvm image.

Override the docker image we are using to build the pipeline

---

orchestration/Chart.yaml

We are encountering problems parsing the latest XML release file from clinvar, due to a large attribute.
* Pulls in an upgraded monster-xml-to-json version that bumps the attribute size limit.

Upgrade monster-xml-to-json to workaround large attribute issue

---

orchestration/scripts/count-processing-history-rows.sh
orchestration/templates/date-present.yaml

If processing fails after data is ingested but before we cut a snapshot (i.e., jade 500s on the snapshot create),
a subsequent retry cannot proceed to the snapshotting test as the current check detects an existing processing_history
row and ends the ingestion job.
Adds a check against version as well as release date; if it misses, it will proceeded with the reingest and cut the snapshot

[DSPDC-1634] Add version to where clause when checking for processing history rows

---

orchestration/templates/process-and-reingest-release.yaml

We can't test the latest change in dev, and we don't want to test it in prod. [Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1656).
Removes the template if statement for checking if the version is pinned specifically for snapshot creation and checking.

ra dspdc 1656 remove version pin snapshot

---

orchestration/templates/process-and-reingest-release.yaml

We removed the check for `versionIsPinned` in a few places in the ingestion pipeline, but there are a few more that need to be removed as they produce output that is needed downstream. Because of the incomplete removal, we are missing needed output and bumping into a template render error captured in this ticket [here](https://broadinstitute.atlassian.net/browse/DSPDC-1659)
* Reverts DataBiosphere/clinvar-ingest#85 until we can figure out a better approach

DSPDC-1659 Fix dev ingest

---

docker/check-snapshot/check.py
docker/check-snapshot/requirements.txt

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1858)
The semantics of the `total` field has changed in the Jade API `enumerateSnapshots` response. Before it reflected the total _after_ filtering, it now reflects the total available. There is a new field, `filteredTotal` that we should begin using.
Since the currently published version of the Jade API client does not support this new field and the clinvar ingest is blocked until we get this resolved, I have switched to making a raw HTTP request via the python `reequests` library.
I have tested this locally using the prod argo config and credentials, no errors and the result is what we expect.

[DSPDC-1858] Workaround jade API change

---

docker/check-snapshot/build.sh
orchestration/templates/process-and-reingest-release.yaml

This docker image needs an image bump and the corresponding workflow needs to point at the new version for the code to take effect.

[DSPDC-1858] Bump check script dockerfile version

---

orchestration/Chart.yaml

This pulls in the BQ 502 retries implemented in [this PR](https://github.com/broadinstitute/monster-helm/pull/47).

[DSPDC-1864] Pull in argo templates with bq 502 fix

---

.github/workflows/build-and-publish-release.yaml
orchestration/templates/process-and-reingest-release.yaml

The clinvar ingest fails to notify when a snapshot is cut, and also fails out when Jade gives back a 500 during the snapshotting process.
* Moves the slack notification for a new snapshot into the template itself, instead of the callsite. 
* Adds argo retries around the Jade check latest snapshot and submit snapshot calls. I'd like to add a retry to the poll snapshot piece as well, but that is brought in via monster-helm and will need to be a PR in that repo.

[DSPDC-1861] Put onExit hook inside of template, add retries

---

orchestration/scripts/poll-ingest-job.py

The polling endpoint is intermittently 502ing, causing the overall job to hang. Given that this is usually a transient condition, we should accept 5XX status codes and retry.

[DSPDC-1895] Retry on poll 5xx from Jade

---

orchestration/templates/ingest-clinvar-release-e2e.yaml

The templating for the `shouldExportDiffs` variable was not rendering properly during testing in dev. I've verified that this renders correctly.

Fix templating for shouldExportDiffs var

---

orchestration/example-values/no-version.yaml
orchestration/example-values/pinned-version.yaml
orchestration/templates/cron-workflow.yaml
orchestration/templates/date-absent.yaml
orchestration/templates/date-present.yaml
orchestration/templates/dual-writer-cron-workflow.yaml
orchestration/templates/export-diff.yaml
orchestration/templates/ingest-clinvar-release-e2e.yaml
orchestration/templates/ingest-xml-archive.yaml
orchestration/templates/process-and-reingest-release.yaml
orchestration/templates/process-xml-release.yaml
orchestration/values.schema.json

The original approach for dual writing was going to be to create a new "clinvar-real-prod" deployment in monster-deploy. This has proven to not be workable.
The alternative approach implemented in this PR is to parameterize the Jade connection information at the top of the workflow and have that flow into all downstream templates. This PR adds a new "dual-writer" cron workflow that is a copy of the existing cron-workflow, but wiring in "alternate" jade connection values (i.e., real prod connection values).
NOTE: This is an updated version of #99 ; instead of adding the jade connection info as parameters to all templates, I've taken a "middle path" approach of making them workflow global vars and changed the helm jade values references to workflow param references in-place. I think this is …

Parameterize jade connection information (mk3)

---

orchestration/templates/cron-workflow.yaml
orchestration/templates/dual-writer-cron-workflow.yaml
orchestration/templates/ingest-xml-archive.yaml
orchestration/templates/process-and-reingest-release.yaml

There are a few other slack notifications that need channel ID parameteried. This PR pushes the channel ID to a global workflow var and updates the related templates.

Parameterize channel ID

---

orchestration/templates/ingest-xml-archive.yaml
orchestration/templates/process-xml-release.yaml

We cannot download an archive from TDR unless it has been included in a snapshot, which does not take place until the _end_ of the ingest. This always worked on our legacy dataset because the argo runner was given permissions ad-hoc, but we will not have these permissions in our new dataset.
So, we need to store the archive in our GCS staging area at the beginning of the ingest and stop pulling it down from TDR.

Do not download archive from TDR

---

orchestration/templates/process-xml-release.yaml

We had a job fail when pulling the archive from GCS to the local volume  due to a 404 from GCS. Assuming this is a transient GCS issue we should retry a few times before giving up.

Retry on error when pulling data from GCS

---

transformation/src/main/scala/org/broadinstitute/monster/clinvar/ArchiveBranches.scala
transformation/src/test/scala/org/broadinstitute/monster/clinvar/ArchiveBranchesSpec.scala

We are creating duplicate entries in the `trait_mapping` table. We should distinct on the list of `trait_mappings` prior to outputting the JSON to GCS for ingest to TDR.

Dedupe on trait mappings
