DataBiosphere/clinvar-ingest

src/jade-schema/tables/submission.table.json

DSPDC-646 Add additional_submitter_ids.

---

README.md

ClinVar ingest process overview doc added to readme, lmk if it needs more/less of anything.

Ra dspdc 655 clinvar doc

---

src/argo/workflow.yaml

And pull in other fixes from testing.

DSPDC-686 Parameterize FTP path.

---

Jenkinsfile

Noticed we hadn't set up publishing for clinvar-ingest yet. Need to merge this in before we can add steps for running the transformation docker from within Argo.

DSPDC-794 Publish artifacts on merge / tags.

---

orchestration/templates/cron-workflow.yaml
orchestration/templates/extract-xml-to-json.yaml
orchestration/templates/ingest-clinvar-archive.yaml
orchestration/templates/rsync-to-gcs.yaml
orchestration/values.schema.json
orchestration/values.yaml

In which Dan discovers a horrible Argo hack that would be nice to package into a library

DSPDC-803 Bump our XML->JSON tool, and adjust following upload logic

---

orchestration/templates/extract-xml-to-json.yaml
orchestration/templates/ingest-clinvar-archive.yaml
orchestration/templates/rsync-to-gcs.yaml
orchestration/templates/run-dataflow.yaml
orchestration/values.schema.json
orchestration/values.yaml
project/plugins.sbt

Successful Argo workflow is [here](https://argo.monster-dev.broadinstitute.org/workflows/clinvar/clinvar-ingest-4bv6t). The corresponding Dataflow job is [here](https://console.cloud.google.com/dataflow/jobs/us-central1/2020-03-09_11_24_40-4791821694937571808). There will be matching changes in `monster-deploy` to fill in the new Helm values / to fix up infrastructure.

DSPDC-794 Run Dataflow job after all extraction steps 

---

docker/kafka-python/Dockerfile
docker/kafka-python/build.sh

add dockerfile and build.sh to push to gcr, image is here: https://console.cloud.google.com/gcr/images/broad-dsp-gcr-public/US/monster-kafka-python?gcrImageListsize=30

Ra dspdc 808 kafka client

---

orchestration/scripts/diff-bq-table.sh
orchestration/scripts/extract-bq-table.sh
orchestration/scripts/get-bq-table-size.sh
orchestration/scripts/query-non-null-row-ids.sh
orchestration/scripts/query-non-null-rows.sh
orchestration/templates/_helpers.tpl
orchestration/templates/cron-workflow.yaml
orchestration/templates/diff-table.yaml
orchestration/templates/download-ftp-file.yaml
orchestration/templates/ingest-clinvar-archive.yaml
orchestration/templates/rsync-to-gcs.yaml
orchestration/values.schema.json
orchestration/values.yaml

I've seen the join->query->extract process work for every table, except the very last time I had passed the wrong output format to the extraction for rows-to-append. I've scheduled another test run in dev at 4:45, but I'm confident it's ready for review now!

DSPDC-814 Add remaining steps for BQ-diff template

---

orchestration/templates/cron-workflow.yaml
orchestration/templates/extract-xml-to-json.yaml
project/plugins.sbt
transformation/src/it/scala/org/broadinstitute/monster/clinvar/ClinVarPipelineIntegrationSpec.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedArchive.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedScv.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedVariation.scala

This one is more complicated than the others. In addition to the plugins bump + resulting scalafmt, I bumped some stuff in the `orchestration` workflow.

DSPDC-941 Bump dependencies

---

project/plugins.sbt

DSPDC-856 Bump plugin to pull in typo fix.

---

orchestration/templates/ingest-clinvar-archive.yaml

Haven't tested it yet, waiting for dev to clear up.

DSPDC-980 Ingest release_history row after staging it.

---

orchestration/Chart.yaml
orchestration/scripts/submit-table-ingest.py
orchestration/scripts/submit-table-soft-delete.py
orchestration/templates/process-table.yaml
orchestration/templates/soft-delete-table.yaml

DSPDC-977 Add soft-delete of old rows to pipeline.

---

orchestration/example-values/no-version.yaml
orchestration/example-values/pinned-version.yaml

Same idea as DataBiosphere/encode-ingest#56

DSPDC-1098 Add example values for helm linting.

---

orchestration/templates/ingest-clinvar-archive.yaml
orchestration/templates/ingest-processed-archive.yaml

Testing now, will link to a successful run once I see one

DSPDC-1086 Write release date into ClinGen bucket.

---

orchestration/example-values/no-version.yaml
orchestration/example-values/pinned-version.yaml
orchestration/templates/cron-workflow.yaml
orchestration/values.schema.json
orchestration/values.yaml

Will test this one after #54. Logic is largely copy-pasted from ENCODE.

DSPDC-1054 Add notification step to ClinVar cron.

---

.github/workflows/build-and-publish-master.yaml
.github/workflows/validate-pull-request.yaml
project/plugins.sbt
transformation/src/main/scala/org/broadinstitute/monster/clinvar/ArchiveBranches.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/Args.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/ClinVarPipelineBuilder.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedArchive.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedInterpretation.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedScv.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedScvTraitSet.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedVariation.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/TraitMetadata.scala

Bump plugins and switch to new codegen.

---

schema/src/main/jade-tables/clinical_assertion.table.json
schema/src/main/jade-tables/clinical_assertion_observation.table.json
schema/src/main/jade-tables/clinical_assertion_trait.table.json
schema/src/main/jade-tables/clinical_assertion_trait_set.table.json
schema/src/main/jade-tables/clinical_assertion_variation.table.json
schema/src/main/jade-tables/gene.table.json
schema/src/main/jade-tables/gene_association.table.json
schema/src/main/jade-tables/rcv_accession.table.json
schema/src/main/jade-tables/submission.table.json
schema/src/main/jade-tables/submitter.table.json
schema/src/main/jade-tables/trait.table.json
schema/src/main/jade-tables/trait_mapping.table.json
schema/src/main/jade-tables/trait_set.table.json
schema/src/main/jade-tables/variation.table.json
schema/src/main/jade-tables/variation_archive.table.json
schema/src/main/jade-tables/xml_archive.table.json
transformation/src/main/scala/org/broadinstitute/monster/clinvar/Args.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/ClinVarPipeline.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/ClinVarPipelineBuilder.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedArchive.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedInterpretation.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedScv.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedScvTraitSet.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/ParsedVariation.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/TraitMetadata.scala
transformation/src/test/scala/org/broadinstitute/monster/clinvar/ArchiveBranchesSpec.scala
transformation/src/test/scala/org/broadinstitute/monster/clinvar/parsers/VariationDescendantsSpec.scala

And thread it through the pipeline.
I added an unrelated unit-test to make myself feel better about the coverage.

DSPDC-1149 Add release_date column to every table

---

orchestration/scripts/check-for-release.sh
orchestration/templates/_helpers.tpl
orchestration/templates/cron-workflow.yaml
orchestration/templates/ingest-xml-archive.yaml
orchestration/values.yaml

Step 1 of the new orchestration process! Will link a test run after I reset dev

DSPDC-1150 Create new WorkflowTemplate for ingesting raw XML

---

.github/workflows/build-and-publish-release.yaml
orchestration/Chart.yaml
orchestration/scripts/count-processing-history-rows.sh
orchestration/scripts/request-release-date-snapshot.py
orchestration/templates/process-xml-archive.yaml

I _think_ this scheme makes sense. It'd be much cleaner if we didn't allow for deploying from a git branch. Still need to test it, but opening for early review.

DSPDC-1176 Add provenance-tracking and auto-snapshot steps

---

orchestration/scripts/check-if-processed-today.sh
orchestration/scripts/request-release-date-snapshot.py
orchestration/templates/export-diff.yaml
orchestration/templates/process-and-reingest-release.yaml

check to see if the processing history table has an entry from _today_; if it does, then we need to diff it and notify clingen. If it doesn't, we good. No, there will not be any instances where this lasts so long that the check should return true but the date is now the next date.

ra-DSPDC-1285-history-check

---

orchestration/templates/export-diff.yaml
orchestration/templates/process-and-reingest-release.yaml

mess with version pinning toggle so that I can trigger the backfill process easily

Ra clinvar diff fixes

---

orchestration/scripts/check-if-processed-today.sh
orchestration/scripts/count-processing-history-rows.sh
orchestration/scripts/get-preceding-release-date.sh
orchestration/templates/date-present.yaml
orchestration/templates/export-diff.yaml
orchestration/templates/ingest-xml-archive.yaml

remove pipeline version filters in queries, it was an unnecessary piece in the first place.

Ra clinvar more fixes

---

project/plugins.sbt
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/SCV.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/TraitMetadata.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/VCV.scala
transformation/src/main/scala/org/broadinstitute/monster/clinvar/parsers/Variation.scala
transformation/src/test/scala/org/broadinstitute/monster/clinvar/ArchiveBranchesSpec.scala

Upgrade ingest-utils and pull in a [fix](https://github.com/DataBiosphere/ingest-utils/pull/24) for escaping table names

Upgrade ingest-utils

---

orchestration/scripts/request-release-date-snapshot.py

Monster should have read access to clinvar snapshots.

Add monster as a reader for all clinvar snapshots
